name: CI
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - uses: gradle/actions/setup-gradle@v4
    - run: ./gradlew build
    - run: ./gradlew build
    - run: echo "lolz!" >> frontend/src/lol.ts
    - run: ./gradlew build
    - run: ./gradlew build
    - run: echo "change=true" >> backend/src/main/resources/application.properties
    - run: ./gradlew build
    - run: ./gradlew build
    - run: echo "lolz2!" > frontend/src/lol.ts
    - run: echo "change2=true" >> backend/src/main/resources/application.properties
    - run: ./gradlew build
    - run: ./gradlew build
    
